# Generated by Django 5.0.2 on 2024-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_PK', models.DateField(default='1900-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='D_Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_PK', models.CharField(default=None, max_length=255)),
                ('code_departement', models.CharField(default=None, max_length=255)),
                ('code_region', models.CharField(default=None, max_length=255)),
                ('libelle_departement', models.CharField(default=None, max_length=255)),
                ('libelle_region', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_Vaccine_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_PK', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='F_Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_PK', models.CharField(default=None, max_length=255)),
                ('vaccine_type_FK', models.CharField(default=None, max_length=255)),
                ('geo_FK', models.CharField(default=None, max_length=255)),
                ('date_fK', models.DateField(default='1900-01-01')),
                ('count_dose', models.IntegerField(default=None)),
                ('count_ucdFK', models.IntegerField(default=None)),
            ],
        ),
    ]
