# Generated by Django 5.0.2 on 2024-02-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0002_d_date_d_geo_d_vaccine_type_f_dose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_date',
            name='id',
        ),
        migrations.RemoveField(
            model_name='d_geo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='d_vaccine_type',
            name='id',
        ),
        migrations.RemoveField(
            model_name='f_dose',
            name='date_fK',
        ),
        migrations.RemoveField(
            model_name='f_dose',
            name='id',
        ),
        migrations.AlterField(
            model_name='d_date',
            name='code_PK',
            field=models.DateField(default='1900-01-01', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='code_PK',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_vaccine_type',
            name='code_PK',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='f_dose',
            name='code_PK',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='f_dose',
            name='geo_FK',
            field=models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='data_parser.d_geo'),
        ),
        migrations.AlterField(
            model_name='f_dose',
            name='vaccine_type_FK',
            field=models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='data_parser.d_vaccine_type'),
        ),
        migrations.AddField(
            model_name='f_dose',
            name='date_FK',
            field=models.ForeignKey(default='1900-01-01', on_delete=django.db.models.deletion.CASCADE, to='data_parser.d_date'),
        ),
    ]
