# Generated by Django 5.0.2 on 2024-02-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0003_remove_d_date_id_remove_d_geo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_dose',
            old_name='count_ucdFK',
            new_name='count_ucd',
        ),
    ]
