# Generated by Django 5.0.2 on 2024-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0004_rename_count_ucdfk_f_dose_count_ucd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_dose',
            name='count_dose',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='f_dose',
            name='count_ucd',
            field=models.FloatField(default=None),
        ),
    ]
